export { MailIcon } from "./mail";
export { GridIcon } from "./grid";
export { FlameIcon } from "./flame";
export { SystemIcon } from './system';
export { SunFilledIcon } from "./sun";
export { GithubIcon } from "./github";
export { SearchIcon } from "./search";
export { CircleIcon } from "./circle";
export { DiscordIcon } from "./discord";
export { MoonFilledIcon } from "./moon";
export { TwitterIcon } from "./twitter";
export { AppleIcon } from './apple';
export { GoogleIcon } from './google';
export { OneDriveIcon, OutlookIcon, ExcelIcon, PowerPointIcon, WordIcon, TeamsIcon } from './office';
export { HeartFilledIcon } from "./heart";
export { BirthDayIcon } from "./birthday";
export { LogoIcon, FaviconIcon } from "./brand";
export { MenuIcon } from "./menu";
export { RightArrowIcon, DownArrowIcon } from "./arrow";
export { EyeFilledIcon, EyeSlashFilledIcon } from "./eye";
